require 'json'
require 'open-uri'
require 'time'
require File.expand_path('../../lib/ad', __FILE__)
require File.expand_path('../../lib/job', __FILE__)

name = "Petfinder"
api_key = "98719f8ded45b41f3153f5736d55d162"
pfjs_photo_host = "drpem3xzef3kf.cloudfront.net"   # Extracted from page source

Adoptable::Job.new(name).run do |target_species, target_breeds, target_exclude_breeds, target_gender, target_age, target_zip, target_distance|
 all_ads = []

 target_breeds.each do |breed|
  # Convert zip to geo coords
  geo = `wget -qO- https://www.petfinder.com/v1/locations/geocoder.json --post-data "q=#{target_zip}&api_key=#{api_key}"`
  geo = JSON.parse(geo).first

  # Avoid rate limiting
  sleep(5)

  # https://www.petfinder.com/breeds/dog
  # document.querySelectorAll('.js-breedSearchView-breedLink').forEach(function (e) { console.log('    when \'' + e.innerText.toLowerCase() + '\' then \'' + e.getAttribute('href').split('=')[2] + '\''); })
  breed_id = 
    case breed.downcase
    when 'affenpinscher' then 'Affenpinscher'
    when 'afghan hound' then 'Afghan Hound'
    when 'airedale terrier' then 'Airedale Terrier'
    when 'akbash' then 'Akbash'
    when 'akita' then 'Akita'
    when 'alaskan malamute' then 'Alaskan Malamute'
    when 'american bulldog' then 'American Bulldog'
    when 'american eskimo dog' then 'American Eskimo Dog'
    when 'american hairless terrier' then 'American Hairless Terrier'
    when 'american staffordshire terrier' then 'American Staffordshire Terrier'
    when 'american water spaniel' then 'American Water Spaniel'
    when 'anatolian shepherd' then 'Anatolian Shepherd'
    when 'appenzell mountain dog' then 'Appenzell Mountain Dog'
    when 'australian cattle dog (blue heeler)' then 'Australian Cattle Dog (Blue Heeler)'
    when 'australian kelpie' then 'Australian Kelpie'
    when 'australian shepherd' then 'Australian Shepherd'
    when 'australian terrier' then 'Australian Terrier'
    when 'basenji' then 'Basenji'
    when 'basset hound' then 'Basset Hound'
    when 'beagle' then 'Beagle'
    when 'bearded collie' then 'Bearded Collie'
    when 'beauceron' then 'Beauceron'
    when 'bedlington terrier' then 'Bedlington Terrier'
    when 'belgian shepherd dog sheepdog' then 'Belgian Shepherd Dog Sheepdog'
    when 'belgian shepherd laekenois' then 'Belgian Shepherd Laekenois'
    when 'belgian shepherd malinois' then 'Belgian Shepherd Malinois'
    when 'belgian shepherd tervuren' then 'Belgian Shepherd Tervuren'
    when 'bernese mountain dog' then 'Bernese Mountain Dog'
    when 'bichon frise' then 'Bichon Frise'
    when 'black labrador retriever' then 'Black Labrador Retriever'
    when 'black mouth cur' then 'Black Mouth Cur'
    when 'black russian terrier' then 'Black Russian Terrier'
    when 'black and tan coonhound' then 'Black and Tan Coonhound'
    when 'bloodhound' then 'Bloodhound'
    when 'blue lacy' then 'Blue Lacy'
    when 'bluetick coonhound' then 'Bluetick Coonhound'
    when 'boerboel' then 'Boerboel'
    when 'bolognese' then 'Bolognese'
    when 'border collie' then 'Border Collie'
    when 'border terrier' then 'Border Terrier'
    when 'borzoi' then 'Borzoi'
    when 'boston terrier' then 'Boston Terrier'
    when 'bouvier des flanders' then 'Bouvier des Flanders'
    when 'boxer' then 'Boxer'
    when 'boykin spaniel' then 'Boykin Spaniel'
    when 'briard' then 'Briard'
    when 'brittany spaniel' then 'Brittany Spaniel'
    when 'brussels griffon' then 'Brussels Griffon'
    when 'bull terrier' then 'Bull Terrier'
    when 'bullmastiff' then 'Bullmastiff'
    when 'cairn terrier' then 'Cairn Terrier'
    when 'canaan dog' then 'Canaan Dog'
    when 'cane corso mastiff' then 'Cane Corso Mastiff'
    when 'carolina dog' then 'Carolina Dog'
    when 'catahoula leopard dog' then 'Catahoula Leopard Dog'
    when 'cattle dog' then 'Cattle Dog'
    when 'caucasian sheepdog (caucasian ovtcharka)' then 'Caucasian Sheepdog (Caucasian Ovtcharka)'
    when 'cavalier king charles spaniel' then 'Cavalier King Charles Spaniel'
    when 'chesapeake bay retriever' then 'Chesapeake Bay Retriever'
    when 'chihuahua' then 'Chihuahua'
    when 'chinese crested dog' then 'Chinese Crested Dog'
    when 'chinese foo dog' then 'Chinese Foo Dog'
    when 'chinook' then 'Chinook'
    when 'chocolate labrador retriever' then 'Chocolate Labrador Retriever'
    when 'chow chow' then 'Chow Chow'
    when 'cirneco dell\'etna' then 'Cirneco dell\'Etna'
    when 'clumber spaniel' then 'Clumber Spaniel'
    when 'cockapoo' then 'Cockapoo'
    when 'cocker spaniel' then 'Cocker Spaniel'
    when 'collie' then 'Collie'
    when 'coonhound' then 'Coonhound'
    when 'corgi' then 'Corgi'
    when 'coton de tulear' then 'Coton de Tulear'
    when 'curly-coated retriever' then 'Curly-Coated Retriever'
    when 'dachshund' then 'Dachshund'
    when 'dalmatian' then 'Dalmatian'
    when 'dandi dinmont terrier' then 'Dandi Dinmont Terrier'
    when 'doberman pinscher' then 'Doberman Pinscher'
    when 'dogo argentino' then 'Dogo Argentino'
    when 'dogue de bordeaux' then 'Dogue de Bordeaux'
    when 'dutch shepherd' then 'Dutch Shepherd'
    when 'english bulldog' then 'English Bulldog'
    when 'english cocker spaniel' then 'English Cocker Spaniel'
    when 'english coonhound' then 'English Coonhound'
    when 'english pointer' then 'English Pointer'
    when 'english setter' then 'English Setter'
    when 'english shepherd' then 'English Shepherd'
    when 'english springer spaniel' then 'English Springer Spaniel'
    when 'english toy spaniel' then 'English Toy Spaniel'
    when 'entlebucher' then 'Entlebucher'
    when 'eskimo dog' then 'Eskimo Dog'
    when 'feist' then 'Feist'
    when 'field spaniel' then 'Field Spaniel'
    when 'fila brasileiro' then 'Fila Brasileiro'
    when 'finnish lapphund' then 'Finnish Lapphund'
    when 'finnish spitz' then 'Finnish Spitz'
    when 'flat-coated retriever' then 'Flat-coated Retriever'
    when 'fox terrier' then 'Fox Terrier'
    when 'foxhound' then 'Foxhound'
    when 'french bulldog' then 'French Bulldog'
    when 'galgo spanish greyhound' then 'Galgo Spanish Greyhound'
    when 'german pinscher' then 'German Pinscher'
    when 'german shepherd dog' then 'German Shepherd Dog'
    when 'german shorthaired pointer' then 'German Shorthaired Pointer'
    when 'german spitz' then 'German Spitz'
    when 'german wirehaired pointer' then 'German Wirehaired Pointer'
    when 'giant schnauzer' then 'Giant Schnauzer'
    when 'glen of imaal terrier' then 'Glen of Imaal Terrier'
    when 'golden retriever' then 'Golden Retriever'
    when 'gordon setter' then 'Gordon Setter'
    when 'great dane' then 'Great Dane'
    when 'great pyrenees' then 'Great Pyrenees'
    when 'greater swiss mountain dog' then 'Greater Swiss Mountain Dog'
    when 'greyhound' then 'Greyhound'
    when 'harrier' then 'Harrier'
    when 'havanese' then 'Havanese'
    when 'hound' then 'Hound'
    when 'hovawart' then 'Hovawart'
    when 'husky' then 'Husky'
    when 'ibizan hound' then 'Ibizan Hound'
    when 'icelandic sheepdog' then 'Icelandic Sheepdog'
    when 'illyrian sheepdog' then 'Illyrian Sheepdog'
    when 'irish setter' then 'Irish Setter'
    when 'irish terrier' then 'Irish Terrier'
    when 'irish water spaniel' then 'Irish Water Spaniel'
    when 'irish wolfhound' then 'Irish Wolfhound'
    when 'italian greyhound' then 'Italian Greyhound'
    when 'italian spinone' then 'Italian Spinone'
    when 'jack russell terrier' then 'Jack Russell Terrier'
    when 'jack russell terrier (parson russell terrier)' then 'Jack Russell Terrier (Parson Russell Terrier)'
    when 'japanese chin' then 'Japanese Chin'
    when 'jindo' then 'Jindo'
    when 'kai dog' then 'Kai Dog'
    when 'karelian bear dog' then 'Karelian Bear Dog'
    when 'keeshond' then 'Keeshond'
    when 'kerry blue terrier' then 'Kerry Blue Terrier'
    when 'kishu' then 'Kishu'
    when 'klee kai' then 'Klee Kai'
    when 'komondor' then 'Komondor'
    when 'kuvasz' then 'Kuvasz'
    when 'kyi leo' then 'Kyi Leo'
    when 'labrador retriever' then 'Labrador Retriever'
    when 'lakeland terrier' then 'Lakeland Terrier'
    when 'lancashire heeler' then 'Lancashire Heeler'
    when 'leonberger' then 'Leonberger'
    when 'lhasa apso' then 'Lhasa Apso'
    when 'lowchen' then 'Lowchen'
    when 'maltese' then 'Maltese'
    when 'manchester terrier' then 'Manchester Terrier'
    when 'maremma sheepdog' then 'Maremma Sheepdog'
    when 'mastiff' then 'Mastiff'
    when 'mcnab' then 'McNab'
    when 'miniature pinscher' then 'Miniature Pinscher'
    when 'mountain cur' then 'Mountain Cur'
    when 'mountain dog' then 'Mountain Dog'
    when 'munsterlander' then 'Munsterlander'
    when 'neapolitan mastiff' then 'Neapolitan Mastiff'
    when 'new guinea singing dog' then 'New Guinea Singing Dog'
    when 'newfoundland dog' then 'Newfoundland Dog'
    when 'norfolk terrier' then 'Norfolk Terrier'
    when 'norwegian buhund' then 'Norwegian Buhund'
    when 'norwegian elkhound' then 'Norwegian Elkhound'
    when 'norwegian lundehund' then 'Norwegian Lundehund'
    when 'norwich terrier' then 'Norwich Terrier'
    when 'nova scotia duck-tolling retriever' then 'Nova Scotia Duck-Tolling Retriever'
    when 'old english sheepdog' then 'Old English Sheepdog'
    when 'otterhound' then 'Otterhound'
    when 'papillon' then 'Papillon'
    when 'patterdale terrier (fell terrier)' then 'Patterdale Terrier (Fell Terrier)'
    when 'pekingese' then 'Pekingese'
    when 'peruvian inca orchid' then 'Peruvian Inca Orchid'
    when 'petit basset griffon vendeen' then 'Petit Basset Griffon Vendeen'
    when 'pharaoh hound' then 'Pharaoh Hound'
    when 'pit bull terrier' then 'Pit Bull Terrier'
    when 'plott hound' then 'Plott Hound'
    when 'podengo portugueso' then 'Podengo Portugueso'
    when 'portuguese podengo' then 'Podengo Portugueso'
    when 'portuguese podengo pequeno' then 'Podengo Portugueso'
    when 'pointer' then 'Pointer'
    when 'polish lowland sheepdog' then 'Polish Lowland Sheepdog'
    when 'pomeranian' then 'Pomeranian'
    when 'poodle' then 'Poodle'
    when 'miniature poodle' then 'Poodle'
    when 'toy poodle' then 'Poodle'
    when 'portuguese water dog' then 'Portuguese Water Dog'
    when 'presa canario' then 'Presa Canario'
    when 'pug' then 'Pug'
    when 'puli' then 'Puli'
    when 'pumi' then 'Pumi'
    when 'rat terrier' then 'Rat Terrier'
    when 'redbone coonhound' then 'Redbone Coonhound'
    when 'retriever' then 'Retriever'
    when 'rhodesian ridgeback' then 'Rhodesian Ridgeback'
    when 'rottweiler' then 'Rottweiler'
    when 'saint bernard st. bernard' then 'Saint Bernard St. Bernard'
    when 'saluki' then 'Saluki'
    when 'samoyed' then 'Samoyed'
    when 'sarplaninac' then 'Sarplaninac'
    when 'schipperke' then 'Schipperke'
    when 'schnauzer' then 'Schnauzer'
    when 'scottish deerhound' then 'Scottish Deerhound'
    when 'scottish terrier scottie' then 'Scottish Terrier Scottie'
    when 'sealyham terrier' then 'Sealyham Terrier'
    when 'setter' then 'Setter'
    when 'shar pei' then 'Shar Pei'
    when 'sheep dog' then 'Sheep Dog'
    when 'shepherd' then 'Shepherd'
    when 'shetland sheepdog sheltie' then 'Shetland Sheepdog Sheltie'
    when 'shiba inu' then 'Shiba Inu'
    when 'shih tzu' then 'Shih Tzu'
    when 'siberian husky' then 'Siberian Husky'
    when 'silky terrier' then 'Silky Terrier'
    when 'skye terrier' then 'Skye Terrier'
    when 'sloughi' then 'Sloughi'
    when 'smooth fox terrier' then 'Smooth Fox Terrier'
    when 'south russian ovtcharka' then 'South Russian Ovtcharka'
    when 'spaniel' then 'Spaniel'
    when 'spitz' then 'Spitz'
    when 'staffordshire bull terrier' then 'Staffordshire Bull Terrier'
    when 'standard poodle' then 'Standard Poodle'
    when 'sussex spaniel' then 'Sussex Spaniel'
    when 'swedish vallhund' then 'Swedish Vallhund'
    when 'terrier' then 'Terrier'
    when 'thai ridgeback' then 'Thai Ridgeback'
    when 'tibetan mastiff' then 'Tibetan Mastiff'
    when 'tibetan spaniel' then 'Tibetan Spaniel'
    when 'tibetan terrier' then 'Tibetan Terrier'
    when 'tosa inu' then 'Tosa Inu'
    when 'toy fox terrier' then 'Toy Fox Terrier'
    when 'treeing walker coonhound' then 'Treeing Walker Coonhound'
    when 'vizsla' then 'Vizsla'
    when 'weimaraner' then 'Weimaraner'
    when 'welsh corgi' then 'Welsh Corgi'
    when 'welsh springer spaniel' then 'Welsh Springer Spaniel'
    when 'welsh terrier' then 'Welsh Terrier'
    when 'west highland white terrier westie' then 'West Highland White Terrier Westie'
    when 'wheaten terrier' then 'Wheaten Terrier'
    when 'whippet' then 'Whippet'
    when 'white german shepherd' then 'White German Shepherd'
    when 'wire fox terrier' then 'Wire Fox Terrier'
    when 'wire-haired pointing griffon' then 'Wire-haired Pointing Griffon'
    when 'wirehaired terrier' then 'Wirehaired Terrier'
    when 'xoloitzcuintle (mexican hairless)' then 'Xoloitzcuintle (Mexican Hairless)'
    when 'yellow labrador retriever' then 'Yellow Labrador Retriever'
    when 'yorkie' then 'Yorkshire Terrier Yorkie'
    when 'yorkshire terrier' then 'Yorkshire Terrier Yorkie'
    when 'yorkshire terrier yorkie' then 'Yorkshire Terrier Yorkie'
    else raise "Unknown breed: #{breed}"
    end

  # Convert settings to site-specific codes
  age =
    # TODO: add all ages
    case target_age.downcase
    when 'puppy' then 'Baby'
    else raise "Unknown age: #{target_age}"
    end

  data = "{\"age\":[\"#{age}\"],\"animal\":\"#{target_species}\",\"distance\":\"#{target_distance}\",\"gender\":[\"#{target_gender}\"],\"location\":\"#{geo["postal_code"]}\",\"lat\":\"#{geo["latitude"]}\",\"lon\":\"#{geo["longitude"]}\",\"-require\":[{\"primary_breed\":\"#{breed_id}\"},{\"secondary_breed\":\"#{breed_id}\"}],\"page_number\":0,\"page_size\":18,\"status\":\"Adoptable\",\"sort\":\"geodist() asc, id desc\",\"partialSearch\":0}"
  ads = `wget -qO- https://www.petfinder.com/v1/pets/search.json --post-data "#{URI::encode("query=#{data}&api_key=#{api_key}")}"`
  ads = JSON.parse(ads)["results"]

  ads.reject! { |ad| ad.include?("primary_breed") ? target_exclude_breeds.any? { |b| !ad["primary_breed"].upcase[b.upcase].nil? } : false }
  ads.reject! { |ad| ad.include?("secondary_breed") ? target_exclude_breeds.any? { |b| !ad["secondary_breed"].upcase[b.upcase].nil? } : false }

  all_ads += ads.map { |ad| Adoptable::Ad.new(name, ad["id"], Time.parse(ad["date_updated"]), ad.include?("secondary_breed") ? "#{ad["primary_breed"]} & #{ad["secondary_breed"]}" : ad["primary_breed"], "//#{pfjs_photo_host}#{ad.has_key?("pet_photo") ? ad["pet_photo"][0] : nil}", "https://www.petfinder.com/petdetail/#{ad["id"]}", "#{ad["locality"]}, #{ad["region_code"]}") }
 end

 all_ads
end
